---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: qperf
  name: server
  labels:
    app: qperf-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qperf-server
  template:
    metadata:
      labels:
        app: qperf-server
    spec:
      containers:
      - name: qperf
        image: danielcoman/docker-qperf:latest
        ports:
        - containerPort: 443
        env:
        - name: SERVICE_TYPE
          value: "server"
          # valueFrom:
          #   fieldRef:
          #     fieldPath: metadata.name
        - name: SERVER_PORT
          value: "443"
---
apiVersion: v1
kind: Service
metadata:
  namespace: qperf
  name: server
  labels:
    app: qperf-server
spec:
  ports:
  - port: 443
    name: server
  clusterIP: None
  selector:
    app: qperf-server
